import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve, sep } from 'node:path';

import { ObjectStore } from '../domain/object-store';
import { SignedUrlVerdict, signObjectUrl, verifyObjectUrl } from '../domain/signed-url';

/**
 * The object store, on a local filesystem.
 *
 * **This is the only object store that exists.** Several comments in this
 * module used to describe "the S3 adapter beside it"; there is no such adapter,
 * and saying otherwise made a deployment gap read as a completed one.
 * Deploying this as it stands means documents living on one replica's disk,
 * which is wrong the moment there are two.
 *
 * Signed URLs here are HMAC-signed tokens **the API redeems itself**, rather
 * than links a browser fetches from a bucket. That keeps the expiry and
 * authorisation rules in the service where they hold whichever store is behind
 * them — and it keeps the integrity check reachable, since the bytes pass
 * through a place that can verify them against the checksum recorded at
 * upload.
 */
export class FilesystemObjectStore implements ObjectStore {
  constructor(
    private readonly root: string,
    private readonly signingKey: string,
    private readonly clock: () => Date = () => new Date(),
  ) {
    // A URL is not a directory, and accepting one silently is how this store
    // came to write documents into a folder literally named
    // `https:/objects.internal/` under the process working directory — where
    // they are invisible to anyone looking for them and gone on the next
    // redeploy. The composition root was passing OBJECT_STORE_ENDPOINT, which
    // is the S3 adapter's setting and means nothing here.
    if (/^[a-z][a-z0-9+.-]*:\/\//i.test(root)) {
      throw new Error(
        `FilesystemObjectStore needs a directory, not a URL: got "${root}". `
        + 'Set OBJECT_STORE_LOCAL_PATH, or use the S3 adapter for a remote endpoint.',
      );
    }
  }

  // `contentType` is accepted and ignored: a filesystem has nowhere to record
  // it. S3 stores it as object metadata, and the interface carries it so the
  // two stores are called identically rather than the caller having to know
  // which one is behind it.
  async put(key: string, bytes: Buffer, _contentType?: string): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.pathFor(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<boolean> {
    try {
      await rm(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  // Signing lives in the domain, shared with the S3 store. The scheme is a
  // property of how this API hands out documents, not of where the bytes are.
  signedUrl(key: string, expiresInSeconds: number): Promise<string> {
    return Promise.resolve(signObjectUrl(this.signingKey, key, expiresInSeconds, this.clock()));
  }

  verifySignedUrl(
    key: string, expiresAt: number, nonce: string, signature: string,
  ): SignedUrlVerdict {
    return verifyObjectUrl(this.signingKey, key, expiresAt, nonce, signature, this.clock());
  }

  isPubliclyReadable(): Promise<boolean> {
    // A local directory is not served by anything. The S3 adapter answers this
    // by actually attempting an unauthenticated read.
    return Promise.resolve(false);
  }

  private pathFor(key: string): string {
    // Key traversal: a key is generated by this service, but a key that reached
    // here from anywhere else must not be able to address a path outside the
    // root.
    //
    // The separator on the end is load-bearing. Comparing against the bare root
    // let `../objects-evil/x` through, because `/data/objects-evil/x` starts
    // with `/data/objects` — a sibling directory whose name merely begins with
    // the root's passes a prefix test. That is the exact case the guard was
    // written for.
    const root = resolve(this.root);
    const path = resolve(join(root, key));
    if (path !== root && !path.startsWith(root + sep)) {
      throw new Error('object key escapes the store root');
    }
    return path;
  }
}
