import { createHmac, randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';

import { ObjectStore } from '../domain/object-store';

/**
 * The object store, on a local filesystem.
 *
 * Used in development and by the tests. The S3 adapter beside it is what
 * deployments use; both satisfy one interface and one shared contract suite, so
 * a behaviour one has and the other does not is a failing test.
 *
 * Signed URLs here are HMAC-signed tokens the API redeems itself, rather than
 * links a browser fetches from a bucket. That is a real difference from S3 and
 * it is why the expiry and authorisation rules live in the service rather than
 * in the store: the rules must hold whichever store is behind them.
 */
export class FilesystemObjectStore implements ObjectStore {
  constructor(
    private readonly root: string,
    private readonly signingKey: string,
    private readonly clock: () => Date = () => new Date(),
  ) {}

  // `contentType` is accepted and ignored: a filesystem has nowhere to record
  // it. S3 stores it as object metadata, and the interface carries it so the
  // two stores are called identically rather than the caller having to know
  // which one is behind it.
  async put(key: string, bytes: Buffer, _contentType?: string): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.pathFor(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<boolean> {
    try {
      await rm(this.pathFor(key));
      return true;
    } catch {
      return false;
    }
  }

  signedUrl(key: string, expiresInSeconds: number): Promise<string> {
    const expiresAt = Math.floor(this.clock().getTime() / 1000) + expiresInSeconds;
    // A nonce, so the same key issued twice produces two distinct URLs and one
    // cannot be mistaken for a stable address.
    const nonce = randomUUID();
    const signature = this.sign(key, expiresAt, nonce);
    return Promise.resolve(`/documents/content?key=${encodeURIComponent(key)}&expires=${expiresAt}&n=${nonce}&sig=${signature}`);
  }

  verifySignedUrl(key: string, expiresAt: number, nonce: string, signature: string): 'ok' | 'expired' | 'invalid' {
    if (this.sign(key, expiresAt, nonce) !== signature) return 'invalid';
    if (expiresAt * 1000 <= this.clock().getTime()) return 'expired';
    return 'ok';
  }

  isPubliclyReadable(): Promise<boolean> {
    // A local directory is not served by anything. The S3 adapter answers this
    // by actually attempting an unauthenticated read.
    return Promise.resolve(false);
  }

  private sign(key: string, expiresAt: number, nonce: string): string {
    return createHmac('sha256', this.signingKey).update(`${key}:${expiresAt}:${nonce}`).digest('base64url');
  }

  private pathFor(key: string): string {
    // Key traversal: a key is generated by this service, but a key that reached
    // here from anywhere else must not be able to address a path outside the
    // root.
    const path = resolve(join(this.root, key));
    if (!path.startsWith(resolve(this.root))) {
      throw new Error('object key escapes the store root');
    }
    return path;
  }
}
