import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { REGISTER } from './personal-data';

/**
 * No credential appears in anything the server actually sends.
 *
 * The register says which columns are credentials. The recorded responses are
 * real bytes from the real controllers. Putting the two together is the only
 * check here that is evidence rather than reasoning: every other guard asserts
 * that a particular code path behaves, and this one asserts that the whole
 * surface, as it really answers, contains nothing it should not.
 *
 * It is deliberately blunt — a substring search over the whole file. A field
 * renamed on its way to the wire would slip past it, which is why
 * `assertNoSecrets` exists as well, inside the one payload assembled from
 * arbitrary rows. Two imperfect checks looking from opposite ends.
 */

const SAMPLES = join(__dirname, '../../../../contract/response-samples.json');

const camel = (name: string): string =>
  name.replace(/_([a-z0-9])/g, (_, character: string) => character.toUpperCase());

it('never sends a credential field, across every recorded response', () => {
  const secrets = Object.values(REGISTER)
    .flatMap((columns) => Object.entries(columns))
    .filter(([, rule]) => rule.dataClass === 'secret')
    .map(([column]) => column);

  expect(secrets.length).toBeGreaterThan(0);

  let recorded: string;
  try {
    recorded = readFileSync(SAMPLES, 'utf8');
  } catch {
    // The evidence is generated by `npm run emit:samples`. Skipping loudly
    // rather than passing quietly: a check that silently does nothing when its
    // input is missing is worse than no check.
    throw new Error(
      `no recorded responses at ${SAMPLES}. Run \`npm run emit:samples\` — this check has `
      + 'nothing to look at without them.',
    );
  }

  const found = secrets.filter((column) =>
    recorded.includes(`"${column}"`) || recorded.includes(`"${camel(column)}"`));

  expect(found).toEqual([]);
});

it('never sends a value that looks like stored credential material', () => {
  // Field names can be renamed; the shapes of the values are harder to hide.
  const recorded = readFileSync(SAMPLES, 'utf8');

  const shapes: [string, RegExp][] = [
    ['a scrypt verifier', /scrypt\$\d+\$/],
    ['a bcrypt hash', /\$2[aby]\$\d{2}\$/],
    ['a PEM private key', /BEGIN [A-Z ]*PRIVATE KEY/],
    ['an AWS access key id', /AKIA[0-9A-Z]{16}/],
    // A bearer token in a response body would mean a token echoed somewhere it
    // was not asked for. The auth endpoints return `accessToken`, which is not
    // recorded, so any JWT-shaped value here is one that leaked.
    ['a JWT', /eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\./],
  ];

  const found = shapes.filter(([, pattern]) => pattern.test(recorded)).map(([what]) => what);

  expect(found).toEqual([]);
});
