import { Controller, Get, Inject, Param, Query } from '@nestjs/common';
import { z } from 'zod';

import { ProblemException } from '../../common/problem/problem';
import { SQL_CLIENT } from '../../persistence/persistence.module';
import { SqlClient } from '../../persistence/sql-client';
import { RequireScopes } from '../identity/transport/guards/public.decorator';

/**
 * The LGU's business directory, as an officer sees it.
 *
 * DELIBERATELY NOT `GET /businesses`. That route answers "which businesses do
 * I own" and is scoped to the caller's own applicant row; no staff role holds
 * `profile:read`, so an officer calling it would get an empty list rather than
 * an error — the worst possible failure, because it looks like an answer. The
 * two questions are different and so are the routes.
 *
 * ── What this does NOT serve, and why ───────────────────────────────────
 *
 * The portal's Businesses screen shows more than this. Its detail view is
 * generated by a seeded PRNG — linked permits, documents, users and an activity
 * feed, all invented from the business id so that reloading shows the same
 * fiction twice. Its list row carries `subdomain` and `userCount`, which are
 * leftovers from a multi-tenant template and describe nothing in this domain.
 *
 * None of that is served here. Inventing a `subdomain` column to satisfy a
 * placeholder would create a vocabulary the LGU never asked for and would then
 * have to keep — which is exactly how the notification catalogue acquired
 * twenty-four invented types. What IS served is what the database actually
 * knows: the business, its owner, and the applications genuinely linked to it.
 * The gap is recorded in the Master Command rather than filled with a guess.
 */

const filtersShape = z.object({
  q: z.string().min(1).max(120).optional(),
  category: z.enum(['Retail', 'Food Service', 'Services', 'Manufacturing', 'Wholesale', 'Other']).optional(),
  status: z.enum(['Active', 'Inactive']).optional(),
}).strict();

/**
 * Named columns, never `b.*` or `ap.*`.
 *
 * A select-star sends whatever the next migration adds — owner ids, audit
 * columns, a field added for an unrelated feature — to every officer's browser,
 * and nobody reviews a disclosure that happened by default. The applicant join
 * makes that sharper here than on the applicant's own route: this reaches every
 * business in the LGU, so a column added to `applicants` would be broadcast
 * about people the caller has no relationship with.
 */
const SELECT = `
  select b.id, b.name, b.category, b.street, b.barangay, b.city, b.province,
         b.registration_number,
         to_char(b.date_registered, 'YYYY-MM-DD') as date_registered,
         b.status, b.created_at,
         ap.id as owner_applicant_id,
         ap.first_name || ' ' || ap.last_name as owner_name,
         acc.email as owner_email,
         acc.mobile_number as owner_mobile_number,
         (select count(*)::int from applications a where a.business_id = b.id) as application_count
    from businesses b
    join applicants ap on ap.id = b.owner_applicant_id
    join accounts acc on acc.id = ap.account_id
`;

interface BusinessRow {
  id: string; name: string; category: string; street: string; barangay: string;
  city: string; province: string; registration_number: string; date_registered: string;
  status: string; created_at: Date; owner_applicant_id: string; owner_name: string;
  owner_email: string; owner_mobile_number: string | null; application_count: number;
}

function onTheWire(row: BusinessRow): Record<string, unknown> {
  return {
    id: row.id,
    name: row.name,
    category: row.category,
    street: row.street,
    barangay: row.barangay,
    city: row.city,
    province: row.province,
    registrationNumber: row.registration_number,
    dateRegistered: row.date_registered,
    status: row.status,
    createdAt: row.created_at.toISOString(),
    // The owner is one applicant, by schema: `owner_applicant_id` is a single
    // not-null column. The portal's "user count" has no counterpart here, and a
    // constant 1 dressed as a count would be worse than its absence.
    owner: {
      applicantId: row.owner_applicant_id,
      name: row.owner_name,
      email: row.owner_email,
      mobileNumber: row.owner_mobile_number,
    },
    applicationCount: row.application_count,
  };
}

@Controller('staff/businesses')
export class StaffBusinessesController {
  constructor(@Inject(SQL_CLIENT) private readonly db: SqlClient) {}

  @Get()
  @RequireScopes('applications:read')
  async list(@Query() query: unknown): Promise<Record<string, unknown>> {
    const result = filtersShape.safeParse(query ?? {});
    if (!result.success) {
      throw ProblemException.validation(
        result.error.issues.map((issue) => ({
          pointer: `/${issue.path.join('/')}`, message: issue.message,
        })),
      );
    }
    const filters = result.data;

    const where: string[] = [];
    const values: unknown[] = [];
    const bind = (value: unknown): string => {
      values.push(value);
      return `$${values.length}`;
    };

    if (filters.category !== undefined) where.push(`b.category = ${bind(filters.category)}`);
    if (filters.status !== undefined) where.push(`b.status = ${bind(filters.status)}`);
    if (filters.q !== undefined) {
      // Name or registration number.
      //
      // The term is escaped, not merely parameterised. Binding a value keeps SQL
      // injection out, and does NOTHING about pattern injection: `%` and `_` are
      // wildcards to ILIKE wherever they come from, so a search for '%' matched
      // every business rather than the businesses with a percent sign in their
      // name. That is a filter quietly answering a different question, and it
      // was caught by a test asserting the opposite of what the code did.
      const escaped = filters.q.replace(/([\\%_])/g, '\\$1');
      const term = bind(`%${escaped}%`);
      where.push(`(b.name ilike ${term} escape '\\' or b.registration_number ilike ${term} escape '\\')`);
    }

    const rows = await this.db.query<BusinessRow>(
      `${SELECT} ${where.length > 0 ? `where ${where.join(' and ')}` : ''} order by b.name`,
      values,
    );
    return { data: rows.rows.map(onTheWire) };
  }

  @Get(':businessId')
  @RequireScopes('applications:read')
  async detail(@Param('businessId') businessId: string): Promise<Record<string, unknown>> {
    if (!/^[0-9a-fA-F-]{36}$/.test(businessId)) {
      throw ProblemException.notFound('No such business.');
    }
    const rows = await this.db.query<BusinessRow>(`${SELECT} where b.id = $1`, [businessId]);
    const business = rows.rows[0];
    if (business === undefined) throw ProblemException.notFound('No such business.');

    // The REAL linkage, not a generated one. Every application that names this
    // business, with the fields an officer needs to open it.
    const applications = await this.db.query<{
      id: string; reference_number: string; permit_type: string; application_action: string;
      lifecycle_status: string; submitted_at: Date | null;
    }>(
      `select id, reference_number, permit_type, application_action, lifecycle_status, submitted_at
         from applications where business_id = $1 order by created_at desc`,
      [businessId],
    );

    return {
      ...onTheWire(business),
      applications: applications.rows.map((row) => ({
        id: row.id,
        referenceNumber: row.reference_number,
        permitType: row.permit_type,
        applicationAction: row.application_action,
        lifecycleStatus: row.lifecycle_status,
        submittedAt: row.submitted_at === null ? null : row.submitted_at.toISOString(),
      })),
    };
  }
}
