import {
  Body, Controller, Get, Headers, HttpCode, HttpStatus, Inject, Param, Patch, Post, Query, Req,
} from '@nestjs/common';
import { z } from 'zod';

import { ProblemException, ProblemType } from '../../common/problem/problem';
import { SQL_CLIENT } from '../../persistence/persistence.module';
import { SqlClient } from '../../persistence/sql-client';
import { Caller } from '../applications/domain/application';
import type { AuthenticatedRequest } from '../identity/transport/guards/authentication.guard';
import { RequireScopes } from '../identity/transport/guards/public.decorator';
import { AuditService } from '../compliance/application/audit.service';
import { StaffBusinessRegistrationService } from './staff-business-registration.service';
import { IN_PROGRESS_STATUSES } from './in-progress-statuses';

/**
 * The LGU's business directory, as an officer sees it.
 *
 * DELIBERATELY NOT `GET /businesses`. That route answers "which businesses do
 * I own" and is scoped to the caller's own applicant row; no staff role holds
 * `profile:read`, so an officer calling it would get an empty list rather than
 * an error — the worst possible failure, because it looks like an answer. The
 * two questions are different and so are the routes.
 *
 * ── What this does NOT serve, and why ───────────────────────────────────
 *
 * The portal's Businesses screen shows more than this. Its detail view is
 * generated by a seeded PRNG — linked permits, documents, users and an activity
 * feed, all invented from the business id so that reloading shows the same
 * fiction twice. Its list row carries `subdomain` and `userCount`, which are
 * leftovers from a multi-tenant template and describe nothing in this domain.
 *
 * None of that is served here. Inventing a `subdomain` column to satisfy a
 * placeholder would create a vocabulary the LGU never asked for and would then
 * have to keep — which is exactly how the notification catalogue acquired
 * twenty-four invented types. What IS served is what the database actually
 * knows: the business, its owner, and the applications genuinely linked to it.
 * The gap is recorded in the Master Command rather than filled with a guess.
 */

// The real, current `businesses.category` vocabulary — see migration 041's
// own comment: businesses.controller.ts's self-service registration route
// widened this list first, and this filter (and onBehalfShape in
// staff-applications.controller.ts) had drifted to the older six-value one,
// so a real "Construction"/"Transport"/"Agriculture" business (which a
// citizen can genuinely register today) could never be filtered for here.
const filtersShape = z.object({
  q: z.string().min(1).max(120).optional(),
  category: z.enum([
    'Retail', 'Food Service', 'Services', 'Manufacturing',
    'Construction', 'Transport', 'Agriculture', 'Other',
  ]).optional(),
  status: z.enum(['Active', 'Inactive']).optional(),
}).strict();

/**
 * Named columns, never `b.*` or `ap.*`.
 *
 * A select-star sends whatever the next migration adds — owner ids, audit
 * columns, a field added for an unrelated feature — to every officer's browser,
 * and nobody reviews a disclosure that happened by default. The applicant join
 * makes that sharper here than on the applicant's own route: this reaches every
 * business in the LGU, so a column added to `applicants` would be broadcast
 * about people the caller has no relationship with.
 */
const SELECT = `
  select b.id, b.name, b.category, b.street, b.barangay, b.city, b.province,
         b.registration_number,
         to_char(b.date_registered, 'YYYY-MM-DD') as date_registered,
         b.status, b.created_at,
         ap.id as owner_applicant_id,
         ap.first_name || ' ' || ap.last_name as owner_name,
         acc.id as owner_account_id,
         acc.email as owner_email,
         acc.mobile_number as owner_mobile_number,
         (acc.photo_key is not null) as owner_has_photo,
         (select count(*)::int from applications a where a.business_id = b.id) as application_count
    from businesses b
    join applicants ap on ap.id = b.owner_applicant_id
    join accounts acc on acc.id = ap.account_id
`;

interface BusinessRow {
  id: string; name: string; category: string; street: string; barangay: string;
  city: string; province: string; registration_number: string; date_registered: string;
  status: string; created_at: Date; owner_applicant_id: string; owner_name: string;
  owner_account_id: string; owner_email: string; owner_mobile_number: string | null;
  owner_has_photo: boolean; application_count: number;
}

function onTheWire(row: BusinessRow): Record<string, unknown> {
  return {
    id: row.id,
    name: row.name,
    category: row.category,
    street: row.street,
    barangay: row.barangay,
    city: row.city,
    province: row.province,
    registrationNumber: row.registration_number,
    dateRegistered: row.date_registered,
    status: row.status,
    createdAt: row.created_at.toISOString(),
    // The owner is one applicant, by schema: `owner_applicant_id` is a single
    // not-null column. The portal's "user count" has no counterpart here, and a
    // constant 1 dressed as a count would be worse than its absence.
    owner: {
      applicantId: row.owner_applicant_id,
      // The account id, not the applicant id — GET /staff/citizens/:id/photo
      // (staff-citizens.controller.ts) is keyed on accounts.id, the same id
      // space the Citizens module itself already uses for "citizenId".
      accountId: row.owner_account_id,
      name: row.owner_name,
      email: row.owner_email,
      mobileNumber: row.owner_mobile_number,
      // Whether to even ask for a photo — same reason staff-queue.service.ts
      // sends `applicantHasPhoto` on every row: twenty businesses should not
      // become twenty 404s to find out none of their owners set one.
      hasPhoto: row.owner_has_photo,
    },
    applicationCount: row.application_count,
  };
}

/**
 * The caller, as the domain understands it. Mirrors
 * `staff-applications.controller.ts`'s own `callerOf` — throws rather than
 * returning a nullable, because a request that reached a guarded handler
 * without claims is a wiring fault, not a client error.
 */
function callerOf(request: AuthenticatedRequest): Caller {
  const claims = request.caller;
  if (claims === undefined) {
    throw new ProblemException(
      ProblemType.unauthorized, 'Authentication is required', HttpStatus.UNAUTHORIZED,
    );
  }
  return { accountId: claims.sub, kind: claims.kind, scopes: claims.scopes };
}

/**
 * What an officer may correct on the LGU's own copy of a business record.
 *
 * Same subset as `businesses.controller.ts`'s own `businessUpdateShape` and
 * for the same reason: `registrationNumber`/`dateRegistered` are the
 * government's own record, not a value this endpoint rewrites, and `status`
 * is its own action below rather than a field here.
 */
const businessUpdateShape = z.object({
  name: z.string().min(1).max(200),
  category: z.enum([
    'Retail', 'Food Service', 'Services', 'Manufacturing',
    'Construction', 'Transport', 'Agriculture', 'Other',
  ]),
  street: z.string().min(1).max(200),
  barangay: z.string().min(1).max(120),
  city: z.string().min(1).max(120),
  province: z.string().min(1).max(120),
}).strict();

/**
 * The Admin Portal's Communication Center. `message` is free text with no
 * template, unlike everything else `notifications` carries — every other
 * row's title/body come from the closed catalogue an application lifecycle
 * event fills in (catalog.ts, notifications module). This is the one path
 * where an officer writes the words a citizen will read directly, so the
 * cap is generous but not unbounded.
 */
const announcementShape = z.object({
  message: z.string().min(1).max(2000),
  audience: z.enum(['all', 'active']),
}).strict();

const registrationShape = z.object({
  owner: z.object({
    firstName: z.string().min(1).max(80),
    lastName: z.string().min(1).max(80),
    // Required, and the schema is why: `applicants.account_id` is NOT NULL and
    // an account needs a unique address. An owner with no email cannot be
    // registered until that constraint changes -- which is a schema decision.
    email: z.string().email().max(320),
    mobileNumber: z.string().min(7).max(20).optional(),
  }).strict(),
  business: z.object({
    name: z.string().min(1).max(200),
    category: z.enum([
      'Retail', 'Food Service', 'Services', 'Manufacturing',
      'Construction', 'Transport', 'Agriculture', 'Other',
    ]),
    street: z.string().min(1).max(200),
    barangay: z.string().min(1).max(120),
    city: z.string().min(1).max(120),
    province: z.string().min(1).max(120),
    registrationNumber: z.string().min(1).max(60),
    dateRegistered: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'must be YYYY-MM-DD'),
  }).strict(),
}).strict();

@Controller('staff/businesses')
export class StaffBusinessesController {
  constructor(
    @Inject(SQL_CLIENT) private readonly db: SqlClient,
    private readonly registration: StaffBusinessRegistrationService,
    private readonly audit: AuditService,
  ) {}

  /**
   * The Communication Center's real backing route.
   *
   * Reuses the existing `account-update` notification type rather than
   * inventing a new one. `notifications.type` is a mirror of the MOBILE
   * CLIENT's own closed enum (catalog.ts's own doc comment) — a type this
   * endpoint invented would be one the shipped mobile app has never seen,
   * and every reader of that enum (mobile's switch, this API's own
   * `notification.service.ts::feed`) would have to guess how to render it.
   * `account-update` is already a known, handled type on every reader; only
   * `title`/`body` are free text here, which the schema already allows —
   * they are stored per-row, never derived from the catalogue at read time.
   *
   * A single INSERT ... SELECT, not one round trip per business owner: a
   * few hundred businesses is a few hundred rows in one statement, not a
   * few hundred statements.
   */
  @Post('announcements')
  @HttpCode(HttpStatus.OK)
  @RequireScopes('staff:administer')
  async broadcastAnnouncement(
    @Req() request: AuthenticatedRequest,
    @Body() body: unknown,
  ): Promise<Record<string, unknown>> {
    const caller = callerOf(request);
    if (caller.kind !== 'staff') {
      throw new ProblemException(
        ProblemType.forbidden, 'Not permitted', HttpStatus.FORBIDDEN, 'This route serves LGU staff.',
      );
    }
    const result = announcementShape.safeParse(body);
    if (!result.success) {
      throw ProblemException.validation(
        result.error.issues.map((issue) => ({ pointer: `/${issue.path.join('/')}`, message: issue.message })),
      );
    }
    const { message, audience } = result.data;

    // `distinct` because one owner can hold more than one business — without
    // it, an owner of three businesses would get the same notice three times
    // for a single broadcast.
    const inserted = await this.db.query<{ account_id: string }>(
      `insert into notifications (account_id, type, title, body)
       select distinct ap.account_id, 'account-update', $1, $2
         from businesses b
         join applicants ap on ap.id = b.owner_applicant_id
         ${audience === 'active' ? "where b.status = 'Active'" : ''}
       returning account_id`,
      ['Announcement from the LGU', message],
    );

    await this.audit.append({
      action: 'announcement.broadcast',
      subjectType: 'business',
      subjectId: null,
      outcome: 'allowed',
      actorAccountId: caller.accountId,
      actorRole: caller.kind,
      afterState: { audience, recipientCount: inserted.rows.length, message },
    });

    return { recipientCount: inserted.rows.length };
  }

  /**
   * Registering a business at the counter -- the "+ Business" wizard's real
   * backing endpoint. Declared before `:businessId` for the same reason
   * `staff-applications.controller.ts`'s `archive` is: Nest matches routes in
   * declaration order, and a POST here never collides with the GET below
   * regardless, but keeping creation next to `list()` keeps the read/write
   * pair for this collection together.
   */
  @Post()
  @HttpCode(HttpStatus.CREATED)
  @RequireScopes('applications:write')
  async create(
    @Req() request: AuthenticatedRequest,
    @Body() body: unknown,
    @Headers('idempotency-key') idempotencyKey?: string,
  ): Promise<Record<string, unknown>> {
    const result = registrationShape.safeParse(body);
    if (!result.success) {
      throw ProblemException.validation(
        result.error.issues.map((issue) => ({
          pointer: `/${issue.path.join('/')}`, message: issue.message,
        })),
      );
    }
    const key = z.string().uuid('must be a UUID').safeParse(idempotencyKey ?? null);
    if (!key.success) {
      throw ProblemException.validation(
        key.error.issues.map((issue) => ({ pointer: '/idempotencyKey', message: issue.message })),
      );
    }
    const input = result.data;

    const created = await this.registration.create({
      caller: callerOf(request),
      owner: {
        firstName: input.owner.firstName,
        lastName: input.owner.lastName,
        email: input.owner.email,
        mobileNumber: input.owner.mobileNumber ?? null,
      },
      business: input.business,
      idempotencyKey: key.data,
    });

    if (!created.ok) {
      if (created.reason === 'key-reused') {
        throw new ProblemException(
          ProblemType.conflict, 'That key was used for a different request',
          HttpStatus.CONFLICT, created.detail,
        );
      }
      throw new ProblemException(
        ProblemType.unprocessable, 'The registration could not be accepted',
        HttpStatus.UNPROCESSABLE_ENTITY, created.detail,
      );
    }

    return {
      businessId: created.businessId,
      applicantId: created.applicantId,
      // Said plainly, because the officer is standing in front of the owner it
      // concerns: nothing has been emailed, and the owner cannot sign in until
      // they set a password through account recovery.
      ownerNextStep: created.accountCreated
        ? 'The owner sets a password through account recovery before they can sign in online.'
        : null,
    };
  }

  @Get()
  @RequireScopes('applications:read')
  async list(
    @Req() request: AuthenticatedRequest,
    @Query() query: unknown,
  ): Promise<Record<string, unknown>> {
    // Defense in depth: the guard already refuses a non-staff caller on any
    // `/staff/*` path, structurally. This is the second, independent check
    // the guard's own doc comment describes -- the one that would have caught
    // the leak this route already caused once even if the guard's path check
    // had a gap, rather than this being the only thing standing in the way.
    if (callerOf(request).kind !== 'staff') {
      throw new ProblemException(
        ProblemType.forbidden, 'Not permitted', HttpStatus.FORBIDDEN, 'This route serves LGU staff.',
      );
    }
    const result = filtersShape.safeParse(query ?? {});
    if (!result.success) {
      throw ProblemException.validation(
        result.error.issues.map((issue) => ({
          pointer: `/${issue.path.join('/')}`, message: issue.message,
        })),
      );
    }
    const filters = result.data;

    const where: string[] = [];
    const values: unknown[] = [];
    const bind = (value: unknown): string => {
      values.push(value);
      return `$${values.length}`;
    };

    if (filters.category !== undefined) where.push(`b.category = ${bind(filters.category)}`);
    if (filters.status !== undefined) where.push(`b.status = ${bind(filters.status)}`);
    if (filters.q !== undefined) {
      // Name or registration number.
      //
      // The term is escaped, not merely parameterised. Binding a value keeps SQL
      // injection out, and does NOTHING about pattern injection: `%` and `_` are
      // wildcards to ILIKE wherever they come from, so a search for '%' matched
      // every business rather than the businesses with a percent sign in their
      // name. That is a filter quietly answering a different question, and it
      // was caught by a test asserting the opposite of what the code did.
      const escaped = filters.q.replace(/([\\%_])/g, '\\$1');
      const term = bind(`%${escaped}%`);
      where.push(`(b.name ilike ${term} escape '\\' or b.registration_number ilike ${term} escape '\\')`);
    }

    const rows = await this.db.query<BusinessRow>(
      `${SELECT} ${where.length > 0 ? `where ${where.join(' and ')}` : ''} order by b.name`,
      values,
    );
    return { data: rows.rows.map(onTheWire) };
  }

  @Get(':businessId')
  @RequireScopes('applications:read')
  async detail(
    @Req() request: AuthenticatedRequest,
    @Param('businessId') businessId: string,
  ): Promise<Record<string, unknown>> {
    // See `list()`: the same second, independent check.
    if (callerOf(request).kind !== 'staff') {
      throw new ProblemException(
        ProblemType.forbidden, 'Not permitted', HttpStatus.FORBIDDEN, 'This route serves LGU staff.',
      );
    }
    if (!/^[0-9a-fA-F-]{36}$/.test(businessId)) {
      throw ProblemException.notFound('No such business.');
    }
    const rows = await this.db.query<BusinessRow>(`${SELECT} where b.id = $1`, [businessId]);
    const business = rows.rows[0];
    if (business === undefined) throw ProblemException.notFound('No such business.');

    // The REAL linkage, not a generated one. Every application that names this
    // business, with the fields an officer needs to open it.
    const applications = await this.db.query<{
      id: string; reference_number: string; permit_type: string; application_action: string;
      lifecycle_status: string; submitted_at: Date | null;
    }>(
      `select id, reference_number, permit_type, application_action, lifecycle_status, submitted_at
         from applications where business_id = $1 order by created_at desc`,
      [businessId],
    );

    return {
      ...onTheWire(business),
      applications: applications.rows.map((row) => ({
        id: row.id,
        referenceNumber: row.reference_number,
        permitType: row.permit_type,
        applicationAction: row.application_action,
        lifecycleStatus: row.lifecycle_status,
        submittedAt: row.submitted_at === null ? null : row.submitted_at.toISOString(),
      })),
    };
  }

  /**
   * Correcting a business's own details on the LGU's behalf — the same
   * owner-editable fields `businesses.controller.ts`'s citizen-facing
   * `update()` changes, reached here without an ownership check because a
   * staff caller may act on any business, not just their own. Same
   * `applications:write` scope `create()` above and `register-business`
   * already use for writing to this table.
   */
  @Patch(':businessId')
  @RequireScopes('applications:write')
  async update(
    @Req() request: AuthenticatedRequest,
    @Param('businessId') businessId: string,
    @Body() body: unknown,
  ): Promise<Record<string, unknown>> {
    if (callerOf(request).kind !== 'staff') {
      throw new ProblemException(
        ProblemType.forbidden, 'Not permitted', HttpStatus.FORBIDDEN, 'This route serves LGU staff.',
      );
    }
    const result = businessUpdateShape.safeParse(body);
    if (!result.success) {
      throw ProblemException.validation(
        result.error.issues.map((issue) => ({ pointer: `/${issue.path.join('/')}`, message: issue.message })),
      );
    }
    const input = result.data;

    const existing = await this.db.query<{ id: string }>('select id from businesses where id = $1', [businessId]);
    if (existing.rows[0] === undefined) throw ProblemException.notFound('No such business.');

    const updated = await this.db.query<BusinessRow>(
      `update businesses
          set name = $2, category = $3, street = $4, barangay = $5, city = $6, province = $7,
              updated_at = now()
        where id = $1
        returning id`,
      [businessId, input.name, input.category, input.street, input.barangay, input.city, input.province],
    );
    const savedId = updated.rows[0]?.id;
    // The columns this endpoint needs to answer with (owner name/email, application
    // count) live only in SELECT's own join, not in a plain `update ... returning`.
    const full = await this.db.query<BusinessRow>(`${SELECT} where b.id = $1`, [savedId]);
    return onTheWire(full.rows[0]!);
  }

  /**
   * Marks a business Inactive on the LGU's behalf. Same reasoning as
   * `businesses.controller.ts`'s own `deactivate`: a hard delete is never
   * possible once any application references the row (`on delete restrict`,
   * migration 003), and deactivating one with an application still in
   * progress is refused rather than silently accepted.
   */
  @Post(':businessId/deactivate')
  @HttpCode(HttpStatus.OK)
  @RequireScopes('applications:write')
  async deactivate(
    @Req() request: AuthenticatedRequest,
    @Param('businessId') businessId: string,
  ): Promise<Record<string, unknown>> {
    return this.setStatus(request, businessId, 'Inactive');
  }

  /** Reverses `deactivate`. */
  @Post(':businessId/reactivate')
  @HttpCode(HttpStatus.OK)
  @RequireScopes('applications:write')
  async reactivate(
    @Req() request: AuthenticatedRequest,
    @Param('businessId') businessId: string,
  ): Promise<Record<string, unknown>> {
    return this.setStatus(request, businessId, 'Active');
  }

  private async setStatus(
    request: AuthenticatedRequest, businessId: string, status: 'Active' | 'Inactive',
  ): Promise<Record<string, unknown>> {
    if (callerOf(request).kind !== 'staff') {
      throw new ProblemException(
        ProblemType.forbidden, 'Not permitted', HttpStatus.FORBIDDEN, 'This route serves LGU staff.',
      );
    }
    const existing = await this.db.query<{ id: string }>('select id from businesses where id = $1', [businessId]);
    if (existing.rows[0] === undefined) throw ProblemException.notFound('No such business.');

    if (status === 'Inactive') {
      const inProgress = await this.db.query<{ id: string }>(
        `select id from applications where business_id = $1 and lifecycle_status = any($2)`,
        [businessId, IN_PROGRESS_STATUSES],
      );
      if (inProgress.rows[0] !== undefined) {
        throw new ProblemException(
          ProblemType.unprocessable, 'A precondition is unmet', HttpStatus.UNPROCESSABLE_ENTITY,
          'This business has an application still in progress. Deactivate once it is decided.',
        );
      }
    }

    await this.db.query('update businesses set status = $2, updated_at = now() where id = $1', [businessId, status]);
    const full = await this.db.query<BusinessRow>(`${SELECT} where b.id = $1`, [businessId]);
    return onTheWire(full.rows[0]!);
  }
}
