/**
 * Writes the notification catalog to the contract repository as a shared
 * artifact, so the mobile client can assert that every deep link it will be
 * sent resolves to a route it actually has.
 *
 * The backend must not invent routes. Without this the failure is silent: a
 * notification arrives, the applicant taps it, and nothing happens.
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { CATALOG } from '../src/modules/notifications/domain/catalog';

const target = process.argv[2] ?? resolve(__dirname, '../../ebpco-contract/reconciliation/notification-catalog.json');

const document = {
  _comment:
    'GENERATED by ebpco-api/scripts/emit-notification-catalog.ts. NORMATIVE: the closed set of ' +
    'notifications the LGU sends, and the route each one resolves to. Both clients carry a test ' +
    'asserting every deepLink is a route they actually have.',
  contractVersion: '0.1.0',
  catalog: CATALOG.map((entry) => ({
    type: entry.type,
    // The client enum constant this maps to, so the mechanical derivation
    // (kebab-case of the constant) is checkable from both sides rather than
    // asserted on one.
    dartName: entry.dartName,
    category: entry.category,
    priority: entry.priority,
    requiresAction: entry.requiresAction,
    statutory: entry.statutory,
    serverGenerated: entry.serverGenerated,
    deepLink: entry.deepLink,
  })),
};

writeFileSync(target, `${JSON.stringify(document, null, 2)}\n`, 'utf8');
process.stdout.write(`wrote ${target} (${CATALOG.length} entries)\n`);
